platform :ios do
  desc "Deploy ios app on the appstore"

  lane :build_debug do
    match(type: "development")
    cordova(
      platform: 'ios',
      release: false
    )
  end
  lane :build do
    match(type: "appstore")
    cordova(platform: 'ios')
  end

  lane :deploy do
    appstore(ipa: ENV['CORDOVA_IOS_RELEASE_BUILD_PATH'])
  end
end

platform :android do
  desc "Deploy android app on play store"

  lane :build_debug do
    cordova(
      platform: 'android',
      release: false,
    )
  end
  lane :build do
    cordova(
      platform: 'android',
      keystore_path: './ifiske.keystore',
      keystore_alias: 'ifiske',
      keystore_password: '11hjortsparre11'
    )
  end

  lane :deploy do
    supply(apk: ENV['CORDOVA_ANDROID_RELEASE_BUILD_PATH'])
  end
end

